#! /bin/sh

### MONITOR ###
MONITOR_NAME="eDP-1"
EXTERNAL_MONITOR_NAME="HDMI-1-0"

STATUS_EXTERNAL_MONITOR=$(xrandr --query | grep $EXTERNAL_MONITOR_NAME)
if [[ ! $STATUS_EXTERNAL_MONITOR == *disconnected* ]]; then
    xrandr --output $MONITOR_NAME --primary --mode 1920x1080 --output $EXTERNAL_MONITOR_NAME --mode 1920x1080 --rotate normal --left-of $MONITOR_NAME
else
    xrandr --output $EXTERNAL_MONITOR_NAME --off
fi

### WORKSPACES ###
bspc monitor $MONITOR_NAME -d 1 2 3 4 5 6 7 8 9 10
if [[ ! $STATUS_EXTERNAL_MONITOR == *disconnected* ]]; then
	bspc monitor $EXTERNAL_MONITOR_NAME -d m
fi

### STARTUP ###
export GTK_THEME=Adwaita:dark                                                       # Dark theme
export EDITOR=nvim
export PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/home/ayilmaz/.cargo/bin:/home/linuxbrew/.linuxbrew/bin

xsetroot -cursor_name left_ptr &                                                    # Cursor
feh --no-fehbg --bg-max /home/ayilmaz/Media/Pictures/Wallpapers/currentwallpaper &       # Background
setxkbmap tr &                                                                      # Keymap
pgrep -x sxhkd > /dev/null || sxhkd &                                               # Shortcuts
polybar bottom &                                                                   # Polybar Top Bar
polybar top &                                                                       # Polybar Bottom Bar
flameshot &                                                                         # Screenshot system tray icon
clipmenud &
# picom &                                                                             # 
picom --fade-in-step=1 --fade-out-step=1 --fade-delta=0 --no-fading-openclose &
# kdeconnectd &
# kdeconnect-indicator &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &                         # Polkit
#kwalletd6 &

### CONFIG ###
bspc config focus_follows_pointer true
bspc config border_width         2
bspc config window_gap           4
bspc config top_padding          0
bspc config bottom_padding       0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color     "#26F0F1"
bspc config normal_border_color      "#202A25"

