#!/bin/bash

### MONITOR ###
STATUS_EXTERNAL_MONITOR=$(xrandr --query | grep $EXTERNAL_MONITOR_NAME)
if [[ ! $STATUS_EXTERNAL_MONITOR == *disconnected* ]]; then
	displayctl dual
else
    displayctl solo
fi

### STARTUP ###
xset s off										# disable screen saver
xset -dpms										# disable DPMS features
setxkbmap -option altwin:swap_lalt_lwin us		# keymap
xsetroot -cursor_name left_ptr                  # cursor
xwallpaper --maximize ~/.config/wallpaper		# background

pgrep -x sxhkd > /dev/null || sxhkd &           # shortcuts
picom &											# compositor
flameshot &                                     # screenshot tool
clipmenud &										# clipboard
polybar main &									# bar

### BSPWM CONFIG ###
bspc config focus_follows_pointer true
bspc config border_width         2
bspc config window_gap           4
bspc config top_padding          0
bspc config bottom_padding       0

bspc config split_ratio          0.65
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true

### BSPWM RULES ###
bspc rule -a "Weston Compositor" state=floating
bspc rule -a "PacketTracer" state=floating
