#!/bin/bash

roficonfig=~/.config/rofi/display.rasi

# Options
Solo="󰌢"
Dual="󰍹"
Mirror="󰍺"
Auto="󰁨"
options="$Solo\n$Dual\n$Mirror\n$Auto"

choice=$(echo -e "$options" | rofi -config $roficonfig -dmenu -p "Display Menu")

case $choice in 
	$Solo)
		displayctl solo
		;;
	$Dual)
		displayctl left
		;;
	$Mirror)
		displayctl mirror
		;;
	$Auto)
		displayctl auto
		;;
esac
