#!/bin/bash

MODE="$1"

if [ -z "$MODE" ]; then
	echo "Usage: $0 [solo|mirror|left|right|auto]"
	exit 1
fi

INTERNAL="eDP-1"
EXTERNAL="HDMI-1-0"

case "$MODE" in
	solo)
		xrandr --output $INTERNAL --primary --output $EXTERNAL --off
    ;;
	mirror)
		xrandr --output $INTERNAL --auto --primary --output $EXTERNAL --auto --same-as $INTERNAL
    ;;
	left)
		xrandr --output $INTERNAL --primary --output $EXTERNAL --auto --left-of $INTERNAL
    ;;
	right)
		xrandr --output $INTERNAL --primary --output $EXTERNAL --auto --right-of $INTERNAL
    ;;
	auto)
		EXT=$(xrandr --query | grep $EXTERNAL)
		if [[ ! $EXT == *disconnected* ]]; then
			displayctl left
		else
			displayctl solo
		fi
    ;;
	*)
		echo "Unknown mode: $MODE"
		echo "Usage: $0 [solo|mirror|left|right|auto]"
		exit 1
    ;;
esac

xwallpaper --maximize ~/.config/wallpaper # reload wallpaper (sometimes needed)
