#!/bin/bash

options="Solo\nLeft\nRight\nMirror\nAuto"

choice=$(echo -e "$options" | rofi -dmenu -p "Display Menu")

case $choice in
    "Solo")
		displayctl solo
        ;;
    "Left")
        displayctl left
        ;;
    "Right")
        displayctl right
        ;;
	"Mirror")
		displayctl mirror
		;;
    "Auto")
        displayctl auto
        ;;
    *)
        exit 1
        ;;
esac

