#!/bin/bash

options="Power Off\nReboot\nLock\nLog Out\nSuspend\nHibernate"

choice=$(echo -e "$options" | rofi -dmenu -p "Power Menu")

case $choice in
    "Power Off")
        loginctl poweroff
        ;;
    "Reboot")
        loginctl reboot
        ;;
	"Lock")
		xsecurelock
		;;
	"Log Out")
		bspwm_logout
		;;
	"Suspend")
		loginctl suspend
		;;
	"Hibernate")
		loginctl hibernate
		;;
    *)
        exit 1
        ;;
esac

