#!/bin/bash

roficonfig=~/.config/rofi/power.rasi

# Options
poweroff="󰐥"
reboot="󰜉"
lock="󰌾"
options="$poweroff\n$reboot\n$lock"

choice=$(echo -e "$options" | rofi -config $roficonfig -dmenu -p "Display Menu")

case $choice in 
	$poweroff)
		loginctl poweroff
		;;
	$reboot)
		loginctl reboot
		;;
	$lock)
		betterlockscreen -l
		;;
esac
